### ISSUE TITLE
define a code-style/ship a .clang-format

### ISSUE THREAD

**Issue by huelsenfruchtzwerg** [gregjesl/brutezone#13]
At least personaly, I get tired of manually formating files. I like to just use clang-format to autoformat every file I work on and know it's correct.
I don't really care all that much about the specific style.

**Comment by gregjesl** [comment]
@huelsenfruchtzwerg How does #14 look?  I've never used clang-format before today but it looks like a great tool that I'll use elsewhere!

**Comment by huelsenfruchtzwerg** [comment]
Looks good to me. I usually go with one of the BaseStyles (Google or LLVM) and then do some minor adjustments, but this is also fine. I like the result. :)
And yeah, clang-format really is a great tool. You can also integrate it into the CI to automatically reject prs with incorrect formatting. Really helps to keep the style consistent.
