### ISSUE TITLE
Tests do not work in release builds

### ISSUE THREAD

**Issue by noloader** [gregjesl/brutezone#2]
This may be related to [Issue 1](https://github.com/gregjesl/brutezone/issues/1). The typical pattern used by the test files appears to be, use `assert` to crash a program. The problem is, Cmake defines `-DNDEBUG` for release builds. The asserts are removed in release builds.

For example, all of the tests in `add_day.c` are removed when building with Cmake in a standard configuration:

```
int main(void)
{
	time_t gmtime;
	struct tm tm;

	// Get the time of 29 January 1970 at 3 AM
	gmtime = (28 * 86400) + (10 * 3600) + (3 * 60) + 17;

	// Convert to a tm
	secs_to_tm(gmtime, &tm);

	// Add a day
	add_day(&tm);

	// Verify the result
	assert(tm.tm_year == 70);
	assert(tm.tm_mon == 0);
	assert(tm.tm_mday == 30);
	assert(tm.tm_hour == 10);
	assert(tm.tm_min == 3);
	assert(tm.tm_sec == 17);
	assert(tm.tm_wday == 5);

	return 0;
}
```

**Comment by gregjesl** [comment]
@noloader Good point.  I'll think on this one; I'm leaning towards defining a separate macro but using a legitimate test framework might also be the right solution.
