### ISSUE TITLE
Remove `timezone_database.h` from source control

### ISSUE THREAD

**Issue by gregjesl** [gregjesl/brutezone#23]
Now that #12 is closed, `make database` can be added as a dependency to ensure the correct timezone database is generated before the library is compiled.

**Comment by huelsenfruchtzwerg** [comment]
This would add a build dependency on mono/dotnet stuffs, I don't know if that's the best idea. I think something like #24 is more viable.

**Comment by gregjesl** [comment]
If we can get #24 working (which shouldn't be too difficult), I agree.
