### ISSUE TITLE
save flash/memory by grouping aliased/identical Timezones

### ISSUE THREAD

**Issue by huelsenfruchtzwerg** [gregjesl/brutezone#7]
While looking at the generator I was wondering why the single-offset timezones where handled as a special case, 'til I realized it was done to reuse them for multiple timezones.

I then started wondering if this optimization could be applied to larger timezones as well, and as it turns out a fair number of timezones are just aliases, even some bigger ones (e.g. Arctic/Longyearbyen is just an alias for Europe/Oslo ([source](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)), but currently is repeated completely).

I figure instead of treating the single-offset timezones as a special case, we could group all identical timezones regardless of number of offsets.

I had a quick crack at it, but I barely know any C# so I didn't manage to get something that compiles. But I guess it should be "relatively" easy using linq-group-by stuff?

**Comment by gregjesl** [comment]
Great idea!  Implementing this shouldn't be too difficult; it looks like [NodaTime can report which time zones are aliases](https://nodatime.org/2.1.x/api/NodaTime.TimeZones.TzdbDateTimeZoneSource.html#NodaTime_TimeZones_TzdbDateTimeZoneSource_Aliases).  I'll give this a try later this week.

**Comment by huelsenfruchtzwerg** [comment]
Good find! I had another crack at it with thoses docs you found, hope you don't mind.

**Comment by gregjesl** [comment]
Closed by #10
